spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  liquibase:
    default-schema: proj
    liquibase-schema: proj
    change-log: classpath:db/changelog-master.yml
    enabled: true